export type MenuItem = {
  path: string;
  label: string;
  permission?: string;
};

export const menuItems: MenuItem[] = [
  { path: '/admin-react/dashboard', label: 'Dashboard', permission: 'admin_dashboard' },
  { path: '/admin-react/members', label: 'Members', permission: 'show_members' },
  { path: '/admin-react/members/deleted', label: 'Deleted Members', permission: 'deleted_member_show' },
  { path: '/admin-react/members/bulk-upload', label: 'Bulk Member Upload', permission: 'bulk_member_add' },
  { path: '/admin-react/members/reported', label: 'Reported Members', permission: 'view_reported_profile' },
  { path: '/admin-react/members/verification-requests', label: 'Verification Requests', permission: 'approve_member' },
  { path: '/admin-react/members/unapproved-pictures', label: 'Unapproved Pictures', permission: 'show_unapproved_profile_picrures' },
  { path: '/admin-react/religions', label: 'Religions', permission: 'show_religions' },
  { path: '/admin-react/sects', label: 'Sects', permission: 'show_sects' },
  { path: '/admin-react/castes', label: 'Castes', permission: 'show_castes' },
  { path: '/admin-react/sub-castes', label: 'Sub-Castes', permission: 'show_sub_castes' },
  { path: '/admin-react/member-languages', label: 'Member Languages', permission: 'show_member_languages' },
  { path: '/admin-react/countries', label: 'Countries', permission: 'show_countries' },
  { path: '/admin-react/states', label: 'States', permission: 'show_states' },
  { path: '/admin-react/cities', label: 'Cities', permission: 'show_cities' },
  { path: '/admin-react/family-status', label: 'Family Status', permission: 'show_family_status' },
  { path: '/admin-react/family-values', label: 'Family Values', permission: 'show_family_values' },
  { path: '/admin-react/on-behalf', label: 'On Behalf', permission: 'show_on_behalves' },
  { path: '/admin-react/marital-statuses', label: 'Marital Statuses', permission: 'show_marital_status' },
  { path: '/admin-react/annual-salaries', label: 'Annual Salaries', permission: 'show_annual_salary_ranges' },
  { path: '/admin-react/job-titles', label: 'Job Titles', permission: 'show_job_titles' },
  { path: '/admin-react/specialities', label: 'Specialities', permission: 'show_specialities' },
  { path: '/admin-react/profile-option-values', label: 'Profile Option Values', permission: 'show_profile_option_values' },
  { path: '/admin-react/additional-attributes', label: 'Additional Attributes', permission: 'show_additional_profile_attributes' },
  { path: '/admin-react/packages', label: 'Packages', permission: 'show_packages' },
  { path: '/admin-react/package-payments', label: 'Package Payments', permission: 'show_package_payments' },
  { path: '/admin-react/wallet/transactions', label: 'Wallet Transactions', permission: 'wallet_transaction_history' },
  { path: '/admin-react/wallet/manual-requests', label: 'Wallet Manual Requests', permission: 'offline_wallet_recharge_requests' },
  { path: '/admin-react/happy-stories', label: 'Happy Stories', permission: 'show_happy_stories' },
  { path: '/admin-react/blogs', label: 'Blogs', permission: 'show_blogs' },
  { path: '/admin-react/blog-categories', label: 'Blog Categories', permission: 'show_blog_categories' },
  { path: '/admin-react/bulk-notifications', label: 'Bulk Notifications', permission: 'newsletter' },
  { path: '/admin-react/profile-reminders', label: 'Profile Reminders', permission: 'newsletter' },
  { path: '/admin-react/contact-us', label: 'Contact Us', permission: 'show_contact_us_queries' },
  { path: '/admin-react/referral/dashboard', label: 'Referral Dashboard', permission: 'view_referral_dashboard' },
  { path: '/admin-react/referral/settings', label: 'Referral Settings', permission: 'manage_referral_settings' },
  { path: '/admin-react/referral/rules', label: 'Referral Rules', permission: 'manage_referral_rules' },
  { path: '/admin-react/referral/referrals', label: 'Referral Referrals', permission: 'view_referral_dashboard' },
  { path: '/admin-react/referral/rewards', label: 'Referral Rewards', permission: 'view_referral_dashboard' },
  { path: '/admin-react/referral/audit-logs', label: 'Referral Audit Logs', permission: 'view_referral_audit_logs' },
  { path: '/admin-react/support/active', label: 'Support Active', permission: 'show_active_tickets' },
  { path: '/admin-react/support/my', label: 'Support My Tickets', permission: 'show_my_tickets' },
  { path: '/admin-react/support/solved', label: 'Support Solved', permission: 'show_solved_tickets' },
  { path: '/admin-react/support/settings', label: 'Support Settings', permission: 'show_support_categories' },
  { path: '/admin-react/manual-payment-methods', label: 'Manual Payment Methods' },
  { path: '/admin-react/uploaded-files', label: 'Uploaded Files', permission: 'show_uploaded_files' },
  { path: '/admin-react/website/header', label: 'Website Header', permission: 'header' },
  { path: '/admin-react/website/footer', label: 'Website Footer', permission: 'footer' },
  { path: '/admin-react/website/appearances', label: 'Website Appearances', permission: 'appearances' },
  { path: '/admin-react/custom-pages', label: 'Custom Pages', permission: 'show_all_pages' },
  { path: '/admin-react/settings/general', label: 'General Settings', permission: 'general_settings' },
  { path: '/admin-react/settings/smtp', label: 'SMTP Settings', permission: 'smtp_settings' },
  { path: '/admin-react/settings/payment-methods', label: 'Payment Methods', permission: 'payment_methods' },
  { path: '/admin-react/settings/third-party', label: 'Third Party', permission: 'third_party_settings' },
  { path: '/admin-react/settings/social-login', label: 'Social Login', permission: 'social_media_login_settings' },
  { path: '/admin-react/settings/fcm', label: 'FCM', permission: 'firebase_push_notification' },
  { path: '/admin-react/settings/verification-form', label: 'Verification Form', permission: 'manage_member_verification_form' },
  { path: '/admin-react/settings/profile-sections', label: 'Profile Sections', permission: 'manage_profile_sections' },
  { path: '/admin-react/settings/activation', label: 'Activation Settings', permission: 'general_settings' },
  { path: '/admin-react/languages', label: 'Languages', permission: 'show_languages' },
  { path: '/admin-react/currencies', label: 'Currencies', permission: 'show_currencies' },
  { path: '/admin-react/email-templates', label: 'Email Templates', permission: 'email_templates' },
  { path: '/admin-react/staffs', label: 'Staffs', permission: 'show_staffs' },
  { path: '/admin-react/roles', label: 'Roles', permission: 'show_staff_roles' },
  { path: '/admin-react/notifications', label: 'Notifications' },
  { path: '/admin-react/addons', label: 'Addons', permission: 'addon_manager' }
];
